# Generated by Django 4.1.13 on 2024-07-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='media_type',
        ),
    ]
