# Generated by Django 4.1.13 on 2024-07-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_remove_file_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='language_code',
            field=models.CharField(default='ru', max_length=10, verbose_name='код языка'),
        ),
    ]
