# Generated by Django 4.1.13 on 2024-07-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_file_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='language_code',
            field=models.CharField(blank=True, default='ru', max_length=10, null=True, verbose_name='код языка'),
        ),
    ]
